### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by mvolkmann** [Baseflow/flutter-google-api-availability#30]
## 🐛 Bug Report

I installed the package and imported it like this:

```dart
import 'package:google_api_availability/google_api_availability.dart';
```

Then in an async function I did this:

```dart
final availability = await GoogleApiAvailability.instance.checkGooglePlayServicesAvailability(true);
```

When I called function while running in an Android emulator I got this error:

```text
ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: MissingPluginException(No implementation found for method checkPlayServicesAvailability on channel flutter.baseflow.com[/google_api_availability/methods]()
```

### Expected behavior

I expected no error and an indication of whether the Google Play services are available.

### Configuration

**Version:** 3.0.1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @mvolkmann, 

That is interesting, I have just quickly tried using this adding the plugin to the default Flutter app created when running `flutter create` and I wasn't able to reproduce the problem (the output was as expected). Below you'll find the code I used. 

It seems something has gone wrong in your environment. Could you try to run:

```shell
flutter clean
flutter pub get
```

After running these command try to run your app again?

<details>
<summary>pubspec.yaml</summary>

```yaml
name: gaa_issue_30
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_api_availability: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
```

</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_api_availability/google_api_availability.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    GoogleApiAvailability.instance
        .checkGooglePlayServicesAvailability(true)
        .then((isAvailable) =>
            print('Google Play Services installed: $isAvailable'));
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>
